services:
  - type: web
    name: keep-it-fresh-platform
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/keep-it-fresh-platform-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.jdk
